routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//News Index Admin
Route::resource('books', 'BooksController')->middleware('auth');
Route::resource('authors', 'AuthorsController')->middleware('auth');
Route::resource('users',UsersController::class)->middleware('auth');
Auth::routes();
Route::get('/admin', function () {
    return view('admin');
});
Route::get('/', function () {
    return view('admin');
});
Route::get('books/{id}', 'BooksController@show');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Books.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Authors;

class Books extends Model
{
    protected $fillable = ['title', 'detail'];

    public function authors()
    {
    	return $this->belongsToMany('App\Models\Authors', 'authors_books');
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Books;
use App\Models\Authors;
use App\Models\AuthorsBooks;
use Illuminate\Http\Request;
use App\Event;
use Session;
use Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Arr;

class BooksController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $books = Books::latest()->with('authors')->paginate(10);
        if(!is_null($request->session()->get('email'))){
        $email = $request->session()->get('email');
                 $collection = DB::table('users')->where('email', $email)->get();
                 $result = $collection->toArray();  
                 $is_admin = json_encode($result[0]->is_admin);
        } else {
            $is_admin = 0;
        }
        return view('admin.books.index',compact('books', 'is_admin'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $authors = Authors::pluck('name', 'id');
        return view('admin.books.create')->with('authors', $authors);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
    	$this->validate($request, [
            'title' => 'required|max:255|string',
            'detail'=> 'required|text',
    	]);
    	$save_book = Books::create([
            'title' =>  $request->title,
            'detail' =>  $request->detail,
        ]);
        $insertedId = $save_book->id;

        if (!is_null($request->authors_id)) {
            $authors_id = $request->authors_id;
            foreach($authors_id as $auth_id){
                $save = AuthorsBooks::create([
                    'books_id' => $insertedId,
                    'authors_id' => $auth_id 
                ]);
            }
        }

        return redirect()->route('books.index')
            ->with('success','Books updated successfully');
        
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $books = Books::find($id);
        return view('admin.books.show', compact('books'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $books = Books::find($id);
        $authors = Authors::pluck('name', 'id');
        $collection = Arr::flatten(DB::table('authors_books')->select('authors_id')->where('books_id', $id)->get()->pluck('authors_id'));
        //var_dump($collection); die();
        return view('admin.books.edit', compact('books', 'authors', 'collection'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update($id, Request $request)
    {
        DB::table('books')->where('id',$id)->update(array(
            'title' =>  $request->title,
            'detail' =>  $request->detail,
        )); 
        if(!is_null($request->authors_id)){
            $check = Arr::flatten(DB::table('authors_books')->select('authors_id')->where('books_id', $id)->get()->pluck('authors_id'));
            $existed_data = count($check);
            $inserted_data = count($request->authors_id);
            $differenceArray = array_diff($check, $request->authors_id);
            if($inserted_data < $existed_data){
                foreach($differenceArray as $auth_id) {
                    $delete_id = DB::table('authors_books')->select('id')->where('authors_id',$auth_id)->where('books_id', $id)->first(); 
                    $delete = DB::table('authors_books')->where('id',$delete_id->id)->delete();
                }
            } else {
                if (!is_null($request->authors_id)) {
                    $authors_id = $request->authors_id;
                    foreach($authors_id as $auth_id){
                        $check = AuthorsBooks::where('authors_id', '=', $auth_id)->where('books_id', $id)->first();
                        if ($check === null) {
                            $save = AuthorsBooks::create([
                                'books_id' => $id,
                                'authors_id' => $auth_id 
                            ]);
                        }
                    }
                }
            }
        }
        return redirect()->route('books.index')
            ->with('success','Books updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        DB::table('books')
            ->where('id',$id)
            ->delete();
        return redirect()->route('books.index')
            ->with('success','Books deleted successfully');
    }
}

resources/views/admin/books/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Add Books</h3>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('books.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea name="detail" class="form-control"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <select class="form-control select2-multi" name="authors_id[]" multiple="multiple" required="required">
                  @foreach ($authors as $key => $value)
                    <option value="{{ $key }}"> 
                        {{ $value }} 
                    </option>
                  @endforeach    
                </select>
            </div>
            <br>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center" style="margin-top: 20px;">
                <button type="submit" class="btn btn-success">Add Books</button>
            </div>
        </div>

    </form>
<script>
    $('.select2-multi').select2();
</script>
@endsection

resources/views/admin/books/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Edit Books</h3>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('books.update',$books->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" value="{{ $books->title }}" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="form-control" name="detail">{{ $books->detail }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <select class="form-control select2-multi" name="authors_id[]" multiple="multiple" required="required">
                  @foreach ($authors as $key => $value)
                    <option value="{{ $key }}" @if(in_array($key,$collection)) selected @endif>
                        {{ $value }} 
                    </option>
                  @endforeach    
                </select>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center" style="margin-top: 20px;">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>

    </form>
<script>
    $('.select2-multi').select2();
</script>
@endsection

resources/views/admin/books/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Books</h3>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('books.create') }}">Add Books</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="table-responsive">
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Details</th>
                <th>Authors</th>
                <th width="280px">Actions</th>
            </tr>
            @foreach ($books ?? '' as $book)
                <tr>
                    <td>{{ $book->id }}</td>
                    <td>{{ $book->title }}</td>
                    <td>{{ $book->detail }}</td>
                    <td>
                        <ul>
                            @foreach ($book->authors as $auth)
                                <li>{{ $auth->name }}</li>
                            @endforeach
                        </ul>
                    </td>
                    <td>
                        <form action="{{ route('books.destroy',$book->id) }}" method="POST">
                            <a class="btn btn-info" href="{{ route('books.show',$book->id) }}">Show</a>

                            <a class="btn btn-primary" href="{{ route('books.edit',$book->id) }}">Edit</a>

                            @csrf
                            @method('DELETE')
                            @if ($is_admin == 1)
                                <button type="submit" class="btn btn-danger">Delete</button>
                            @endif
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>

    {!! $books ?? ''->links() !!}

@endsection

resources/views/admin/books/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Show Books</h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $books->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {!! $books->detail !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Authors:</strong>
                <ul>
                    @foreach ($books->authors as $auth)
                        <li>{{ $auth->name }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endsection