routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//News Index Admin
Route::resource('books', 'BooksController')->middleware('auth');
Route::resource('authors', 'AuthorsController')->middleware('auth');
Route::resource('users',UsersController::class)->middleware('auth');
Auth::routes();
Route::get('/admin', function () {
    return view('admin');
});
Route::get('/', function () {
    return view('admin');
});
Route::get('books/{id}', 'BooksController@show');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Authors.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Books;

class Authors extends Model
{
    protected $fillable = ['name', 'detail'];

    public function books()
    {
    	return $this->belongsToMany('App\Models\Books', 'authors_books');
    }
}

app/Http/Controllers/AuthorsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Authors;
use App\Models\Books;
use Illuminate\Http\Request;
use App\Event;
use Session;
use Auth;
use Illuminate\Support\Facades\DB;

class AuthorsController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $authors = Authors::latest()->paginate(10);
        if(!is_null($request->session()->get('email'))){
        $email = $request->session()->get('email');
                 $collection = DB::table('users')->where('email', $email)->get();
                 $result = $collection->toArray();  
                 $is_admin = json_encode($result[0]->is_admin);
        } else {
            $is_admin = 0;
        }
        return view('admin.authors.index',compact('authors', 'is_admin'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.authors.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {

    	$save = Authors::create([
            'name' =>  $request->name,
            'detail' =>  $request->detail,
        ]);

        return redirect()->route('authors.index')
            ->with('success','Authors updated successfully');
        
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $authors = Authors::find($id);
        return view('admin.authors.show', compact('authors'));
    }
    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $authors = Authors::find($id);
        return view('admin.authors.edit', compact('authors', 'books'));
    }


    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        DB::table('authors')->where('id',$id)->update(array(
            'name' =>  $request->name,
            'detail' =>  $request->detail,
        )); 
        return redirect()->route('authors.index')
            ->with('success','Authors updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        DB::table('authors')->where('id',$id)
            ->where('id',$id)
            ->delete();
        return redirect()->route('authors.index')
            ->with('success','Authors deleted successfully');
    }
}

resources/views/admin/authors/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Add Authors</h3>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('authors.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea name="detail" class="form-control"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center" style="margin-top: 20px;">
                <button type="submit" class="btn btn-success">Add Authors</button>
            </div>
        </div>

    </form>
@endsection

resources/views/admin/authors/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Edit Authors</h3>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('authors.update',$authors->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $authors->name }}" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea name="detail" class="form-control">{{ $authors->detail }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center" style="margin-top: 20px;">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>

    </form>
@endsection

resources/views/admin/authors/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Authors</h3>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('authors.create') }}">Add Authors</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="table-responsive">
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Details</th>
                <th width="280px">Actions</th>
            </tr>
            @foreach ($authors ?? '' as $auth)
                <tr>
                    <td>{{ $auth->id }}</td>
                    <td>{{ $auth->name }}</td>
                    <td>{{ $auth->detail }}</td>
                    <td>
                        <form action="{{ route('authors.destroy',$auth->id) }}" method="POST">
                            <a class="btn btn-info" href="{{ route('authors.show',$auth->id) }}">Show</a>

                            <a class="btn btn-primary" href="{{ route('authors.edit',$auth->id) }}">Edit</a>

                            @csrf
                            @method('DELETE')
                            @if ($is_admin == 1)
                                <button type="submit" class="btn btn-danger">Delete</button>
                            @endif
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>

    {!! $authors ?? ''->links() !!}

@endsection

resources/views/admin/authors/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3>Show Author</h3>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $authors->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {!! $authors->detail !!}
            </div>
        </div>
    </div>
@endsection